-- table project 
CREATE TABLE IF NOT EXISTS `project` (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  desc TEXT,
  crt_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  upd_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- table tool
CREATE TABLE IF NOT EXISTS `tool` (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  desc TEXT,
  path TEXT,
  version TEXT,
  vendor TEXT,
  arch TEXT,
  config JSON,
  crt_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  upd_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
